// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kssDK80U-wSU--SvzqXPEoEjEPTpQHU',
    appId: '1:78792273613:web:6f87ec50803816ecbf8384',
    messagingSenderId: '78792273613',
    projectId: 'primerproyecto-13f23',
    authDomain: 'primerproyecto-13f23.firebaseapp.com',
    databaseURL: 'https://primerproyecto-13f23-default-rtdb.firebaseio.com',
    storageBucket: 'primerproyecto-13f23.appspot.com',
    measurementId: 'G-Q8DZRLJ3D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBoKu9WrVdgfcuE1gQWvI7HUnABgbvb8',
    appId: '1:78792273613:android:9c5b1be9b44d7781bf8384',
    messagingSenderId: '78792273613',
    projectId: 'primerproyecto-13f23',
    databaseURL: 'https://primerproyecto-13f23-default-rtdb.firebaseio.com',
    storageBucket: 'primerproyecto-13f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjSStLOTUHEnzNaBr5kijuP47exr11Fgc',
    appId: '1:78792273613:ios:0cdf693b937878e9bf8384',
    messagingSenderId: '78792273613',
    projectId: 'primerproyecto-13f23',
    databaseURL: 'https://primerproyecto-13f23-default-rtdb.firebaseio.com',
    storageBucket: 'primerproyecto-13f23.appspot.com',
    iosClientId: '78792273613-3iahs0fj775smocrujj8pimu5mb3n7p9.apps.googleusercontent.com',
    iosBundleId: 'co.edu.ucundinamarca.pproyecto',
  );
}
